FROM php:8.1-apache

RUN apt-get update -y


ARG APACHE_INTERNAL_PORT
ARG MYSQL_DEFAULT_USER
ARG MYSQL_ROOT_PASSWORD
ARG MYSQL_DATABASE

RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

WORKDIR /var/www/html
COPY ./src .

RUN sed -i "s/80/8000/g" /etc/apache2/ports.conf
RUN sed -i "s/localhost/db/g" /var/www/html/db.php
RUN sed -i "s/root/${MYSQL_DEFAULT_USER}/g" /var/www/html/db.php
RUN sed -i "s/password123/${MYSQL_ROOT_PASSWORD}/g" /var/www/html/db.php


CMD ["apachectl", "-D", "FOREGROUND"]
